import { useEffect, useState } from "react";

const severityStyles = {
  info: "bg-sky-500/20 text-sky-200",
  warning: "bg-amber-500/20 text-amber-200",
  critical: "bg-rose-500/20 text-rose-200"
};

export default function App() {
  const [reviews, setReviews] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const loadReviews = async () => {
      try {
        const response = await fetch("/api/reviews");
        const data = await response.json();
        setReviews(data);
      } catch (error) {
        console.error(error);
      } finally {
        setLoading(false);
      }
    };

    loadReviews();
  }, []);

  return (
    <div className="min-h-screen">
      <header className="border-b border-slate-800 bg-slate-950/80 backdrop-blur">
        <div className="mx-auto flex max-w-6xl items-center justify-between px-6 py-5">
          <div>
            <h1 className="text-2xl font-semibold">AI Code Review Assistant</h1>
            <p className="text-sm text-slate-400">
              Monitor pull request reviews generated by the backend service.
            </p>
          </div>
          <span className="rounded-full border border-slate-700 px-3 py-1 text-xs text-slate-300">
            FastAPI + React
          </span>
        </div>
      </header>

      <main className="mx-auto max-w-6xl px-6 py-10">
        <section className="rounded-2xl border border-slate-800 bg-slate-900/40 p-6 shadow-xl">
          <div className="mb-6 flex items-center justify-between">
            <h2 className="text-lg font-semibold">Latest Reviews</h2>
            <span className="text-xs text-slate-400">
              {loading ? "Loading" : `${reviews.length} total`}
            </span>
          </div>

          {loading && (
            <div className="rounded-xl border border-slate-800 bg-slate-950/50 p-6 text-sm text-slate-400">
              Fetching reviews...
            </div>
          )}

          {!loading && reviews.length === 0 && (
            <div className="rounded-xl border border-dashed border-slate-700 bg-slate-950/50 p-6 text-sm text-slate-400">
              No reviews yet. Trigger a webhook or add a review from the API.
            </div>
          )}

          <div className="space-y-4">
            {reviews.map((review) => (
              <article
                key={review.id}
                className="rounded-xl border border-slate-800 bg-slate-950/40 p-5"
              >
                <div className="flex flex-wrap items-center justify-between gap-3">
                  <div>
                    <h3 className="text-base font-semibold text-slate-100">
                      {review.repo} · PR #{review.pr_number || "N/A"}
                    </h3>
                    <p className="text-sm text-slate-400">{review.summary}</p>
                  </div>
                  <span className="rounded-full border border-slate-700 px-3 py-1 text-xs uppercase tracking-wide text-slate-300">
                    {review.status}
                  </span>
                </div>

                {review.comments?.length > 0 && (
                  <div className="mt-4 space-y-3">
                    {review.comments.map((comment, index) => (
                      <div
                        key={`${review.id}-${index}`}
                        className="rounded-lg border border-slate-800 bg-slate-900/50 p-3"
                      >
                        <div className="flex flex-wrap items-center justify-between gap-2">
                          <div className="text-xs text-slate-400">
                            {comment.file_path} · L{comment.line_start}-L{comment.line_end}
                          </div>
                          <span
                            className={`rounded-full px-2 py-0.5 text-[10px] uppercase tracking-wide ${
                              severityStyles[comment.severity] || severityStyles.info
                            }`}
                          >
                            {comment.severity}
                          </span>
                        </div>
                        <p className="mt-2 text-sm text-slate-200">
                          {comment.message}
                        </p>
                      </div>
                    ))}
                  </div>
                )}
              </article>
            ))}
          </div>
        </section>
      </main>
    </div>
  );
}
